### ISSUE TITLE
broken read_phy_files()

### ISSUE THREAD

**Issue by atspaeth** [braingeneers/braingeneerspy#10]
c7f33b0 added a field to `analysis.NeuronAttributes` but didn't update the constructor call in `analysis.read_phy_files()`.

@ashsrobbins please fix this, or maybe we should delete the entire function now that it's been replaced? It seems pretty messy compared to `analysis.load_spike_data()`.

Here's the error reported by @AriSinervo 
![image](https://github.com/braingeneers/braingeneerspy/assets/15931271/9826c0ff-901a-4020-9bb5-010939f49dbf)

**Comment by ashsrobbins** [comment]
#11 
@atspaeth This should do the trick, I am not adding "experiment" to read_phy_files as it is deprecated.
