### ISSUE TITLE
Prints in load_spike_data.

### ISSUE THREAD

**Issue by atspaeth** [braingeneers/braingeneerspy#14]
A lot of the print statements in load_spike_data() aren't skipped even when verbose is false, which is slightly annoying when using it instead of read_phy_files() in code with a progress bar.

Is anyone using these prints (@ashsrobbins @surygeng)?

If you need more granularity than the `verbose` option, can I replace them to calls to logging.log()? I'd be in favor of more logging in general if it's also easy to turn it off.

**Comment by surygeng** [comment]
I don’t need the print statements and I like the idea of logging. Maybe
logger.debug()?

Sury
