### ISSUE TITLE
Optimize datasets to look for local (/public/groups/braingeneers) if it exists

### ISSUE THREAD

**Issue by rcurrie** [braingeneers/braingeneerspy#2]
@atspaeth @ashsrobbins Thinking I should make datasets.load_*() try and see if /public/groups/braingeneers/archive exists and if so read from it. Pro is that it will be much faster when running on GI servers, con is it pretty specific to our environment and the right way to scale is likely k8s jobs on PRP etc....

Opinions?

**Comment by atspaeth** [comment]
Isn't it already really specific to our environment? We have hardcoded subpaths and are using the S3 endpoint environment variable as a basis for HTTP requests.

Maybe just make that origin URL configurable, and modify the two JSON-loading functions to allow filesystem paths in addition to URLs? It could default to accessing our dataset over HTTP like it does now, and people running on GI could change the configuration to get the speed boost.

**Comment by rcurrie** [comment]
Its specific behind the scene. As all the data (so far) is public anyone could run a colab using the library. I have coded the URLs to the CEPH endpoints (external, and now it checks if there is an internal one in case we're running on PRP). This would just add another optimization behind the scenes while retaining the public simplicity. I think I can make it so it will just choose the best automatically - maybe too much magic but at lease no one needs to then deal with the details (unless you are writing to the archive).
