### ISSUE TITLE
Can't load datasets from S3.

### ISSUE THREAD

**Issue by atspaeth** [braingeneers/braingeneerspy#5]
Since 2a9e868 `datasets_electrophysiology.load_data` fails with HTTP 404 when trying to load from S3.

Seems to be inserting the actual endpoint `https://s3-west.nrp-nautilus.io/` instead of `s3://braingeneers/` because the code now uses `get_default_endpoint()` instead of `get_archive_url()`.

@davidparks21

**Comment by ashsrobbins** [comment]
Fixed, switched to using get_basepath() instead of get_default_endpoint. 
commit 7adc8114984a7d4d9ffa8f988dc0913296aa37e7
