### ISSUE TITLE
electrophysiology data and code links in "Protosequences in human cortical organoids model intrinsic states in the developing cortex"

### ISSUE THREAD

**Issue by aghatpande** [braingeneers/braingeneerspy#69]
Hi, congratulations on this great project. I am involved in an organoid project at Penn and have been reading the preprint on 'Protosequences ...".
 I am looking to download parts of the dataset  mentioned in it, which you have generously shared here:  https://dandiarchive.org/dandiset/000732  But was looking for some information on some of the files. For example, could I download only the organoid data (preferably curated but raw would be ok) and also the specific code that was used to analyze the same whose link seems broken at this time: https://github.com/braingeneers/Protosequences2023. Happy to share my own analysis eventually. Best
A. S. Ghatpande

**Comment by atspaeth** [comment]
Whoops, that repo was definitely supposed to be public, sorry! You should be able to see it now
