### ISSUE TITLE
Broken test script.

### ISSUE THREAD

**Issue by atspaeth** [braingeneers/braingeneerspy#8]
If I try to run pytest over the whole repo with `pytest -vv .`, it fails during test discovery at [braingeneers/iot/shadows_test.py:32](https://github.com/braingeneers/braingeneerspy/blob/82cb6eb60aa918441aec3a7c9f9b9e4075a22249/braingeneers/iot/shadows_test.py#L32C13-L32C13).

It's one of those `<<<< HEAD` markers Git uses to indicate merge conflicts. @pvbaudin it looks like you created this. Can you choose the correct resolution for the conflict?

**Comment by atspaeth** [comment]
Looks like this is fixed by 244c244, thanks Pierre!

**Comment by pvbaudin** [comment]
Yeah sorry about that one, the file in question doesn't even contain unit tests, it was more of an active test "playground" script. Didn't realize the naming convention messed with stuff.
